from typing import Any, Callable, Iterable, Mapping

from authlib.oauth2.rfc6749 import OAuth2Token

class OAuth2Client:
    client_id: str | None
    client_secret: str | None
    metadata: dict[str, Any]
    leeway: int
    token_endpoint: str | None

    @property
    def token(self) -> OAuth2Token | None: ...
    @token.setter
    def token(self, token: Mapping[str, Any] | None) -> None: ...
    def register_compliance_hook(self, hook_type: str, hook: Callable[..., Any]) -> None: ...
    def fetch_token(self, url: str | None = None, **kwargs: Any) -> OAuth2Token: ...
    def refresh_token(self, url: str | None = None, refresh_token: str | None = None, **kwargs: Any) -> OAuth2Token: ...
    def ensure_active_token(self, token: OAuth2Token | None = None) -> bool: ...
    def parse_response_token(self, resp: Any) -> OAuth2Token: ...
