# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.0.3.dev0+g87ae998.d20230423'
__version_tuple__ = version_tuple = (3, 0, 3, 'dev0', 'g87ae998.d20230423')
